---
name: "Spotify Import"
guid: "F03D0ADB-289F-4986-BD6F-2468025249B3"
imageUrl: "https://github.com/Viperinius/jellyfin-plugin-spotify-import/raw/master/viperinius-plugin-spotifyimport.png"
version: "1.13.0.0"
targetAbi: "10.10.3.0"
framework: "net8.0"
overview: "This plugin imports playlists from Spotify."
description: >
  This plugin enables you to import playlists from Spotify to your Jellyfin server automatically.
  It provides a scheduled task that queries a given list of Spotify playlists and tries to recreate them as best as possible in Jellyfin.
category: "Metadata"
owner: "Viperinius"
artifacts:
- "Viperinius.Plugin.SpotifyImport.dll"
- "SpotifyAPI.Web.dll"
- "Fastenshtein.dll"
- "Json.More.dll"
- "JsonPointer.Net.dll"
- "JsonSchema.Net.dll"
- "Otp.NET.dll"
#- "Microsoft.Data.Sqlite.dll"            # not needed as long as jellyfin uses the library as well and we keep the version in sync
#- "SQLitePCLRaw.batteries_v2.dll         # 
#- "SQLitePCLRaw.core.dll"                #
#- "SQLitePCLRaw.provider.e_sqlite3.dll"  #
#- "MetaBrainz.Common.dll"       # not needed as long as jellyfin uses the library as well and we keep the version in sync
#- "MetaBrainz.Common.Json.dll"  #
#- "MetaBrainz.MusicBrainz.dll"  #
changelog: |2-
  # Changelog

  ## [1.13.0.0] - 2025-03-24

  ### Added

  - Caching of Spotify playlists (only query the full track data if the playlist state changed)
  - Caching of track matches (reuse match of a track for all occurrences across playlists)

  ### Fixed

  - Fix procedure to aquire auth token for alternative Spotify provider after recent changes made by Spotify (again)

  ## [1.12.4.0] - 2025-03-11

  ### Fixed

  - Fix procedure to aquire auth token for alternative Spotify provider after recent changes made by Spotify

  ## [1.12.3.1] - 2025-01-25
  ## [1.12.3.0] - 2025-01-25

  ### Fixed

  - Fix manual track map path not being found depending on the plugin location
  - Fix exception handling if the manual track map does not exist yet

  ## [1.12.2.0] - 2025-01-07

  ### Fixed

  - Fix parsing of empty artist fields when adding manual map entries

  ## [1.12.1.0] - 2024-12-08

  ### Fixed

  - Fix missing handling of request timeouts when using the alternative Spotify provider

  ## [1.12.0.0] - 2024-12-07

  ### Added

  - Workaround regarding the recent Spotify API changes (#48)

  ## [1.11.0.0] - 2024-11-30

  ### Added

  - Support for manually mapping tracks between Spotify and Jellyfin (#44)

  ### Fixed

  - Keep iterating through artists even after a first match was found (in case multiple artists with the same name exist)
  - Fix exception getting user playlists due to changes in the Spotify API (#46)

  ## [1.10.0.0] - 2024-09-14

  ### Added

  - New option to set playlists as private or public to all users

  ### Fixed

  - Exception if Spotify returns duplicate playlists for a user

  ## [1.9.1.0] - 2024-09-01

  (Internal testing release)

  ## [1.9.0.0] - 2024-08-25

  ### Added

  - New setting to enable imported "progress" to be displayed in the playlist description -> #30
  - New matching type to extract an album name from the track name (like 'Track [From "An Album"]') and use that for comparison

  ### Changed

  - Updated Jellyfin dependencies to match version 10.9.9
  - Switch request handling on plugin config page to use jellyfin custom fetch mechanism

  ## [1.8.2.0] - 2024-08-24

  (Internal testing release)

  ## [1.8.1.1] - 2024-06-21

  ### Fixed

  - Include missing Fastenshtein dependency in build artifacts

  ## [1.8.1.0] - 2024-05-19

  ### Fixed

  - Broken API endpoints (due to authorisation policy changes in Jellyfin introduced in 10.9)

  ## [1.8.0.0] - 2024-05-17

  ### Added

  - Support for Jellyfin 10.9
  - New configurable flag for each playlist whether or not to recreate it from scratch each time the task runs
  - New matching type "fuzzy checking" for track and album names

  ### Changed

  - "Ignore Parentheses" now treats [] the same as ()
  - Some rework of the track matching process (again); the plugin now tries to find all potential matches first and then decides a "best fit" track name

  ## [1.7.2.0] - 2024-03-29

  ### Fixed

  - Accept matches where Spotify uses a different track syntax than metadata providers (e.g. "Track Name - Super Remix" on Spotify and "Track Name (Super Remix)" on MusicBrainz) if at least match level `Ignore Case + Punctuation` is used

  ## [1.7.1.0] - 2024-03-18

  ### Changed

  - Reintroduce the old track matching method as a configurable legacy alternative (not recommended to be used)
  - Extend logging information / debug possibilities

  ## [1.7.0.3] - 2024-03-17

  (Internal testing release)

  ## [1.7.0.2] - 2024-03-17

  (Internal testing release)

  ## [1.7.0.1] - 2024-03-17

  (Internal testing release)

  ## [1.7.0.0] - 2024-03-10

  ### Changed

  - If a track / album / artist contains text in parentheses, this content will be used as another match candidate (e.g. to match tracks that have an english translation of a foreign name)

  ### Fixed

  - Fix broken track matching if multiple artists of a track exist in Jellyfin, but the track is not located under the first existing artist
  - Fix not matching tracks if their album is not a direct child of their artist and (for whatever reason) only detectable via the album artist

  ## [1.6.0.3] - 2024-03-05

  (Internal testing release)

  ## [1.6.0.2] - 2024-03-03

  (Internal testing release)

  ## [1.6.0.1] - 2024-02-27

  (Internal testing release)

  ## [1.6.0.0] - 2024-02-23

  ### Changed

  - Search Jellyfin server for artist instead of individual tracks and narrow track matching down from there
  - Search Jellyfin server using only the first few characters of an artist name to increase chances of finding matches with slightly different names
  - Use all (album) artists from Spotify to check whether a matching artist exists in Jellyfin, not just the first one

  ### Fixed

  - Catch exceptions from Spotify API lib when retrieving users / playlists

  ## [1.5.0.0] - 2023-12-16

  ### Added

  - New switch to control where missing track files are stored
  - Add new matcher to ignore anything in parentheses in track/album/artist names

  ### Fixed

  - Fix Spotify username regex not allowing special characters

  ## [1.4.0.0] - 2023-10-15

  ### Added

  - Auto-migration of plugin configurations from previous plugin versions
  - More verbose logging that can be enabled

  ### Changed

  - Reworked handling of Spotify user IDs to get all their playlists (moved to its own table separate from individual playlist IDs)

  ### Fixed

  - Fix bug in config page that reset all unsaved table row states when adding a new row
  - Fix parsing of Spotify URLs that contain parameters

  ## [1.3.0.0] - 2023-08-13

  ### Added

  - Extend playlist configuration by allowing user IDs as input, which leads to all of their playlists getting imported automatically

  ### Fixed

  - Fix exception if a Spotify track contains no album artists metadata

  ## [1.2.0.0] - 2023-07-01

  ### Added

  - Extend playlist configurability
    - Allow own playlist names
    - Set target owner / user
  - Allow configuration of the track matcher
    - Choose comparison strictness
    - Choose what parts of the metadata get examined / compared

  ## [1.1.1.0] - 2023-05-06

  ### Fixed

  - Fix exception if a Spotify playlist contains "ghost" items / null tracks
  - A missing tracks file is created even though the playlist is not missing any tracks
  - Fix config page not loading values when revisiting without a full page reload

  ## [1.1.0.0] - 2023-04-15

  ### Added

  - New button to delete all generated missing tracks files
  - New option to specify the date format used for missing tracks file names

  ### Fixed

  - A missing tracks file is created even though the playlist is not missing any tracks
  - Fix exception if a song has no artists, album name or album artists set

  ## [1.0.0.0] - 2023-02-26

  - Initial release

  ### Added

  - Spotify authentication via authorization code / PKCE
  - Generation of missing tracks lists
  - Import of Spotify playlists
